<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Olla\Flow\Metadata\Metadata' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Discover.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/DiscoverInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Resource.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Property.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Source.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Admin.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Frontend.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/GraphqlType.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Operation.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Discover/Subscription.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/FactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/Resource.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/Operation.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/Property.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/Subscription.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Factory/Type.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Builder.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/MetadataInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Metadata/Metadata.php';

$a = ($this->privates['Olla\Flow\Config'] ?? $this->load(__DIR__.'/getConfigService.php'));
$b = ($this->privates['annotations.cached_reader'] ?? $this->load(__DIR__.'/getAnnotations_CachedReaderService.php'));
$c = ($this->services['serializer'] ?? $this->load(__DIR__.'/getSerializerService.php'));
$d = ($this->privates['property_info'] ?? $this->load(__DIR__.'/getPropertyInfoService.php'));

$e = new \Olla\Flow\Metadata\Discover\Resource($a, $b, $c, $d);

$f = new \Olla\Flow\Metadata\Discover\Property($a, $b, $c, $d);

$g = new \Olla\Flow\Metadata\Discover\Admin($a, $b, $c, $d);

$h = new \Olla\Flow\Metadata\Discover\Frontend($a, $b, $c, $d);

$i = new \Olla\Flow\Metadata\Discover\GraphqlType($a, $b, $c, $d);

$j = new \Olla\Flow\Metadata\Discover\Operation($a, $b, $c, $d);

$k = new \Olla\Flow\Metadata\Discover\Subscription($a, $b, $c, $d);

return $this->privates['Olla\Flow\Metadata\Metadata'] = new \Olla\Flow\Metadata\Metadata(new \Olla\Flow\Metadata\Builder(new \Olla\Flow\Metadata\Source($a, $e, $f), $g, $h, $i, $j, $e, $k, $f, new \Olla\Flow\Metadata\Factory\Resource(), new \Olla\Flow\Metadata\Factory\Operation(), new \Olla\Flow\Metadata\Factory\Property(), new \Olla\Flow\Metadata\Factory\Subscription(), new \Olla\Flow\Metadata\Factory\Type()), $g, $h, $i, $j, $e, $k, $f);
