<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Olla\Flow\Command\MetadataCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Command/MetadataCommand.php';

return $this->services['console.command.public_alias.Olla\Flow\Command\MetadataCommand'] = new \Olla\Flow\Command\MetadataCommand(($this->privates['Olla\Flow\Metadata\Metadata'] ?? $this->load(__DIR__.'/getMetadataService.php')));
