<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Database\NullDB' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/DBInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/AbstractDB.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/NullDB.php';

return $this->services['Olla\Flow\Database\NullDB'] = new \Olla\Flow\Database\NullDB();
