<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mic0YU\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mic0YU/srcProdProjectContainer.php') {
    touch(__DIR__.'/Container1mic0YU.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\Container1mic0YU\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \Container1mic0YU\srcProdProjectContainer(array(
    'container.build_hash' => '1mic0YU',
    'container.build_id' => 'b386e17c',
    'container.build_time' => 1517562499,
));
