<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Platform\Action\ItemAction' shared service.

return $this->services['Olla\Platform\Action\ItemAction'] = new \Olla\Platform\Action\ItemAction(($this->services['Olla\Platform\Service\QueryService'] ?? $this->load(__DIR__.'/getQueryServiceService.php')));
