<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Security\Guard\NullGuard' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/GuardInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/AbstractGuard.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/NullGuard.php';

return $this->services['Olla\Flow\Security\Guard\NullGuard'] = new \Olla\Flow\Security\Guard\NullGuard();
