<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Validator\NullValidator' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/ValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/AbstractValidator.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/NullValidator.php';

return $this->services['Olla\Flow\Validator\NullValidator'] = new \Olla\Flow\Validator\NullValidator();
