<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Serializer\NullSerializer' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/SerializerInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/AbstractSerializer.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/NullSerializer.php';

return $this->services['Olla\Flow\Serializer\NullSerializer'] = new \Olla\Flow\Serializer\NullSerializer();
