<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Orm\Repository\OrmRepository' shared service.

include_once $this->targetDirs[3].'/vendor/olla/orm/src/Repository/OrmRepository.php';

return $this->services['Olla\Orm\Repository\OrmRepository'] = new \Olla\Orm\Repository\OrmRepository(($this->services['doctrine'] ?? $this->load(__DIR__.'/getDoctrineService.php')));
