<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Orm\ORM' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/DBInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/AbstractDB.php';
include_once $this->targetDirs[3].'/vendor/olla/orm/src/ORM.php';

return $this->services['Olla\Orm\ORM'] = new \Olla\Orm\ORM($this);
