<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Platform\Service\QueryService' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/GuardInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/AbstractGuard.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Guard/Guard.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/DBInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/AbstractDB.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Database/DB.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/SerializerInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/AbstractSerializer.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Serializer/Serializer.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/ValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/AbstractValidator.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Validator/Validator.php';
include_once $this->targetDirs[3].'/vendor/olla/platform/src/Flow/QueryFlow.php';
include_once $this->targetDirs[3].'/vendor/olla/platform/src/Service/ServiceInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/platform/src/Service/QueryService.php';

$a = ($this->privates['Olla\Flow\Config'] ?? $this->load(__DIR__.'/getConfigService.php'));
$b = ($this->privates['Olla\Flow\Service\Service'] ?? $this->load(__DIR__.'/getServiceService.php'));

return $this->services['Olla\Platform\Service\QueryService'] = new \Olla\Platform\Service\QueryService(($this->privates['Olla\Flow\Metadata\Metadata'] ?? $this->load(__DIR__.'/getMetadataService.php')), new \Olla\Flow\Security\Guard\Guard($a, $b), new \Olla\Flow\Database\DB($a, $b), new \Olla\Flow\Serializer\Serializer($a, $b), new \Olla\Flow\Validator\Validator($a, $b));
