<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Olla\Flow\Service\Service' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Service/ServiceInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Service/Service.php';

$this->privates['Olla\Flow\Service\Service'] = $instance = new \Olla\Flow\Service\Service($this);

$instance->addService('operation', 'Olla\\Flow\\Operation\\NullOperation', 'Olla\\Flow\\Operation\\NullOperation');
$instance->addService('guard', 'Olla\\Flow\\Security\\Guard\\NullGuard', 'Olla\\Flow\\Security\\Guard\\NullGuard');
$instance->addService('gate', 'Olla\\Flow\\Security\\Gate\\NullGate', 'Olla\\Flow\\Security\\Gate\\NullGate');
$instance->addService('credential', 'Olla\\Flow\\Security\\Credential\\NullCredential', 'Olla\\Flow\\Security\\Credential\\NullCredential');
$instance->addService('middleware', 'Olla\\Flow\\Security\\Middleware\\NullMiddleware', 'Olla\\Flow\\Security\\Middleware\\NullMiddleware');
$instance->addService('monitor', 'Olla\\Flow\\Monitor\\NullMonitor', 'Olla\\Flow\\Monitor\\NullMonitor');
$instance->addService('storage', 'Olla\\Flow\\Database\\NullDB', 'Olla\\Flow\\Database\\NullDB');
$instance->addService('serializer', 'Olla\\Flow\\Serializer\\NullSerializer', 'Olla\\Flow\\Serializer\\NullSerializer');
$instance->addService('validator', 'Olla\\Flow\\Validator\\NullValidator', 'Olla\\Flow\\Validator\\NullValidator');
$instance->addService('storage', 'orm', 'Olla\\Orm\\ORM');

return $instance;
