<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Olla\Flow\Config' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/ConfigInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Config.php';

$this->privates['Olla\Flow\Config'] = $instance = new \Olla\Flow\Config();

$instance->add('class_collection_operation', 'Olla\\Platform\\Action\\CollectionAction');
$instance->add('class_item_operation', 'Olla\\Platform\\Action\\ItemAction');
$instance->add('class_create_operation', 'Olla\\Platform\\Action\\CreateAction');
$instance->add('class_update_operation', 'Olla\\Platform\\Action\\UpdateAction');
$instance->add('class_delete_operation', 'Olla\\Platform\\Action\\DeleteAction');
$instance->add('bundle_resources_path', array());
$instance->add('bundle_operations_path', array(0 => ($this->targetDirs[3].'/vendor/olla/demo/src/Presentation/Service')));
$instance->add('bundle_admins_path', array(0 => ($this->targetDirs[3].'/vendor/olla/demo/src/Presentation/Admin')));
$instance->add('bundle_frontends_path', array(0 => ($this->targetDirs[3].'/vendor/olla/demo/src/Presentation/Frontend')));
$instance->add('flow_resource_paths', $this->getParameter('flow_resource_paths'));
$instance->add('flow_operation_paths', $this->getParameter('flow_operation_paths'));
$instance->add('flow_admin_paths', $this->getParameter('flow_admin_paths'));
$instance->add('flow_frontend_paths', $this->getParameter('flow_frontend_paths'));

return $instance;
