<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Security\Middleware\NullMiddleware' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Middleware/AbstractMiddleware.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Middleware/NullMiddleware.php';

return $this->services['Olla\Flow\Security\Middleware\NullMiddleware'] = new \Olla\Flow\Security\Middleware\NullMiddleware();
