<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.runtime_cache' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/yaml/Parser.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/ChainableParserInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/Chainable/YamlParser.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/Chainable/PhpParser.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/ParserRegistry.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocator/DefaultFileLocator.php';
include_once $this->targetDirs[3].'/vendor/hautelook/alice-bundle/src/Alice/FileLocator/KernelFileLocator.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/IncludeProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/IncludeProcessor/DefaultIncludeProcessor.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/RuntimeCacheParser.php';

$a = ($this->services['kernel'] ?? $this->get('kernel'));

$b = new \Hautelook\AliceBundle\Alice\FileLocator\KernelFileLocator(new \Nelmio\Alice\FileLocator\DefaultFileLocator(), $a);

return $this->privates['nelmio_alice.file_parser.runtime_cache'] = new \Nelmio\Alice\Parser\RuntimeCacheParser(new \Nelmio\Alice\Parser\ParserRegistry(array(0 => new \Nelmio\Alice\Parser\Chainable\YamlParser(new \Symfony\Component\Yaml\Parser()), 1 => new \Nelmio\Alice\Parser\Chainable\PhpParser())), $b, new \Nelmio\Alice\Parser\IncludeProcessor\DefaultIncludeProcessor($b));
