<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Olla\Flow\Security\Gate\NullGate' shared service.

include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Gate/GateInterface.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Gate/AbstractGate.php';
include_once $this->targetDirs[3].'/vendor/olla/flow/src/Security/Gate/NullGate.php';

return $this->services['Olla\Flow\Security\Gate\NullGate'] = new \Olla\Flow\Security\Gate\NullGate();
