<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZFrNIoz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZFrNIoz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZFrNIoz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZFrNIoz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZFrNIoz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZFrNIoz',
    'container.build_id' => '830cf2cc',
    'container.build_time' => 1517563465,
));
